name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  docker_build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Login to Docker Registry
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build -t io .
          docker tag io andreiionut1411/io:latest
          docker push andreiionut1411/io:latest

  deploy_service:
    name: Deploy Service
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Install Curl
        run: sudo apt-get install curl -y

      # - name: Trigger Deployment
      #   run: |
      #     curl -XPOST http://ip172-18-0-117-covjt2gl2o90008hp42g-9000.direct.labs.play-with-docker.com/api/webhooks/da7c65a6-f9c0-49ae-88ee-6100968637b0
